openapi: "3.0.0"
info:
  version: 1.0.0
  title: NLPortfolio
paths:
  /ping:
    get:
      responses:
        '200':
          description: ping
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Pong'
  /encode-string:
    get:
      responses:
        '200':
          description: Return a semantic vector for any string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncodedVector'

  /rag-reply:
    get:
      responses:
        '200':
          description: Return a rag reply for a query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RagReply'

components:
  schemas:

    Pong:
      type: string
      example: pong

    EncodedVector:
      type: object
      required:
        - EncodedVector
      properties:
        EncodedVector:
          type: array
          items:
            type: number
            example: 1.01

    RagReply:
      type: object
      required:
        - RagReply
      properties:
        RagReply:
          type: string
          example: Hello world!
